# app
spring.application.name=tienda-universitaria
server.port=8080

# postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=unpapupro
spring.datasource.driver-class-name=org.postgresql.Driver


# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


security.jwt.secret=1234abcd
security.jwt.expiration-seconds=3600

jwt.secret=mi_clave_super_segura_para_jwt_de_minimo_32_caracteres_2026
jwt.expiration=86400000